AllCops:
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 256

AllCops:
  Exclude:
    - 'lib/tasks/cucumber.rake'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'test/test_helper.rb'
    - 'config/application.rb'
    - 'db/schema.rb'
    - 'features/**/*'
